name: Chrome Extension

on:
  push:
    branches:
      - main
    paths:
      - chrome-extension/**
      - .github/workflows/chrome-extension.yaml
  pull_request:
    branches:
      - main
    paths:
      - chrome-extension/**
      - .github/workflows/chrome-extension.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chrome-extension

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Formatting
        run: npm run test:format
